---
name: Dictionary Pipeline
on:
  workflow_dispatch:
    inputs:
      word:
        description: 'Word to fetch definition for'
        required: true

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Lint-check
        uses: Anuj359/Actions/lint-check@main

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Python script
        env:
          DICTIONARY_API_KEY: ${{ secrets.DICTIONARY_API_KEY }}
        run: make run ARG1="${{ github.event.inputs.word }}"
        # If the line length is an issue, split the run command into multiple lines
        # run: |
        #   ls  # Check the directory contents
        #   echo "Word: ${{ github.event.inputs.word }}"
        #   python3 task.py ${{ github.event.inputs.word }}
